SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B
ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY B.CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC
