SELECT CAR_ID, CASE WHEN CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE TO_DATE('20221016','YYYYMMDD') >= START_DATE AND TO_DATE('20221016','YYYYMMDD') <= END_DATE) THEN '대여중'
ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;