SELECT USER_ID, UGU.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY USER_ID, UGU.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;