SELECT II.ITEM_ID , II.ITEM_NAME , II.RARITY
FROM ITEM_TREE IT
JOIN ITEM_INFO II
ON IT.ITEM_ID = II.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN (SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY = 'RARE')
ORDER BY IT.ITEM_ID DESC;