SELECT T.ITEM_ID, (SELECT ITEM_NAME FROM ITEM_INFO WHERE ITEM_ID = T.ITEM_ID) AS ITEM_NAME,
(SELECT RARITY FROM ITEM_INFO WHERE ITEM_ID = T.ITEM_ID) AS RARITY
FROM ITEM_INFO I
LEFT OUTER JOIN ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE RARITY = 'RARE' AND PARENT_ITEM_ID IS NOT NULL
ORDER BY T.ITEM_ID DESC;