SELECT TO_NUMBER(TO_CHAR(START_DATE,'MM')), CAR_ID, COUNT(*) AS RECORDES
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE >= TO_DATE('20220801','YYYYMMDD') AND START_DATE < TO_DATE('20221101','YYYYMMDD')
AND CAR_ID IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE >= TO_DATE('20220801','YYYYMMDD') AND START_DATE < TO_DATE('20221101','YYYYMMDD')
GROUP BY CAR_ID 
HAVING COUNT(*) >= 5) 
GROUP BY TO_NUMBER(TO_CHAR(START_DATE,'MM')), CAR_ID
ORDER BY TO_NUMBER(TO_CHAR(START_DATE,'MM')), CAR_ID DESC;