SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SkILLCODES WHERE NAME = 'Python') = (SELECT CODE FROM SkILLCODES WHERE NAME = 'Python')
OR SKILL_CODE & (SELECT CODE FROM SkILLCODES WHERE NAME = 'C#') = (SELECT CODE FROM SkILLCODES WHERE NAME = 'C#')
ORDER BY ID