SELECT DISTINCT(CCC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR  CCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY  CCRH
ON CCC.CAR_ID = CCRH.CAR_ID
WHERE MONTH(START_DATE) = 10 AND CAR_TYPE = '세단'
ORDER BY CCC.CAR_ID DESC;
